sylius_grid:
    grids:
        sylius_bot_subscriber:
            driver:
                options:
                    class: "%sylius_bot_plugin.model.bot_subscriber.class%"
            fields:
                profile_picture:
                    label: sylius_bot_plugin.bot_subscriber.profile_picture
                    type: twig
                    options:
                        template: "@SyliusBotPlugin/Ui/Image.html.twig"
                name:
                    label: sylius_bot_plugin.bot_subscriber.name
                    type: string
                locale:
                    label: sylius_bot_plugin.bot_subscriber.locale
                    type: string
                gender:
                    label: sylius_bot_plugin.bot_subscriber.gender
                    type: string
                channel:
                    label: sylius_bot_plugin.bot_subscriber.channel
                    type: twig
                    options:
                        template: "@SyliusBotPlugin/Ui/Channel.html.twig"
            
            actions:
                #        main:
                #          create:
                #            type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
            filters:
                name:
                    label: sylius_bot_plugin.bot_subscriber.name
                    type: string
                first_name:
                    label: sylius_bot_plugin.bot_subscriber.first_name
                    type: string
                last_name:
                    label: sylius_bot_plugin.bot_subscriber.last_name
                    type: string
                locale:
                    label: sylius_bot_plugin.bot_subscriber.locale
                    type: string
                timezone:
                    label: sylius_bot_plugin.bot_subscriber.timezone
                    type: string
                gender:
                    label: sylius_bot_plugin.bot_subscriber.gender
                    type: select
                    form_options:
                        choices:
                            sylius_bot_plugin.bot_subscriber.male: male
                            sylius_bot_plugin.bot_subscriber.female: female
                channel:
                    label: sylius_bot_plugin.bot_subscriber.channel
                    type: select
                    form_options:
                        choices:
                            sylius_bot_plugin.bot_subscriber.messenger: Messenger
                            sylius_bot_plugin.bot_subscriber.telegram: Telegram
