# Define your own admin routes here
ahmedkhd_bot:
  resource: |
    alias: sylius_bot_plugin.bot
    except: ['show']
    section: admin
    templates: "@SyliusAdmin\\Crud"
    grid: sylius_bot_plugin
  type: sylius.resource
