# Define your own admin routes here
ahmedkhd_bot:
  resource: |
    alias: sylius_bot_plugin.bot
    except: ['show', 'update', 'create']
    section: admin
    templates: "@AhmedkhdSyliusBotPlugin"
    grid: sylius_bot_plugin
  type: sylius.resource

ahmedkhd_bot_subscriber:
  resource: |
    alias: sylius_bot_plugin.bot_subscriber
    except: ['create']
    section: admin
    templates: "@SyliusAdmin\\Crud"
    grid: sylius_bot_subscriber
  type: sylius.resource
