# Define your own admin routes here
sylius_bot_plugin_facebook_persistent_menu:
  path: /bots
  methods: [GET, POST]
  defaults:
    _controller: sylius_bot_plugin.controller.facebook:facebookHome
    _sylius:
      template: "@SyliusBotPlugin/Facebook/connectMessenger.html.twig"
      form: SyliusBotPlugin\Form\PersistentMenuFormType

sylius_bot_plugin_facebook_connect_page:
  path: /bots/connect
  methods: [POST]
  defaults:
    _controller: sylius_bot_plugin.controller.facebook:facebookConnectPage

sylius_bot_plugin_bot_subscriber:
  resource: |
    alias: sylius_bot_plugin.bot_subscriber
    except: ['create']
    section: admin
    templates: "@SyliusAdmin\\Crud"
    grid: sylius_bot_subscriber
  type: sylius.resource
