# Define your own admin routes here
ahmedkhd_facebook_persistent_menu:
  path: /bots
  methods: [GET, POST]
  defaults:
    _controller: ahmedkhd_sylius_bot_plugin.controller.facebook:facebookConnect
    _sylius:
      template: "@AhmedkhdSyliusBotPlugin/Facebook/connectMessenger.html.twig"
      form: Ahmedkhd\SyliusBotPlugin\Form\PersistentMenuFormType


ahmedkhd_bot_subscriber:
  resource: |
    alias: sylius_bot_plugin.bot_subscriber
    except: ['create']
    section: admin
    templates: "@SyliusAdmin\\Crud"
    grid: sylius_bot_subscriber
  type: sylius.resource
