# Define your own admin routes here
ahmedkhd_sylius_bot_plugin_admin_bots_messenger:
  path: /bots/messenger
  defaults:
    _controller: ahmedkhd_sylius_bot_plugin.controller.bots:connectMessageAction
    name: ~
