# Define your own admin routes here
ahmedkhd_bot:
  resource: |
    alias: sylius_bot_plugin.bot
    except: ['show', 'update', 'create']
    section: admin
    templates: "@AhmedkhdSyliusBotPlugin"
    grid: sylius_bot_plugin
  type: sylius.resource
