
services:
  sylius_bot_plugin.listener.admin.menu_builder:
    class: SyliusBotPlugin\Menu\MenuBuilderListener
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

  sylius_bot_plugin.controller.webhook:
    class: SyliusBotPlugin\Controller\WebhookController
    tags: ['controller.service_arguments']
    public: true
    arguments:
      - '@service_container'
      - '@logger'
      - '@sylius_bot_plugin.service.facebook_messenger'

  sylius_bot_plugin.controller.facebook:
    class: SyliusBotPlugin\Controller\FacebookController
    tags: ['controller.service_arguments']
    public: true
    arguments:
      - '@service_container'
      - '@logger'
      - '@sylius_bot_plugin.service.facebook_messenger'
      - '@form.factory'

  sylius_bot_plugin.service.facebook_messenger:
    class: SyliusBotPlugin\Service\FacebookMessengerService
    public: true
    arguments:
      - '@service_container'
      - '@logger'
      - '@serializer'

  sylius_bot_plugin.service.bot_configuration:
    class: SyliusBotPlugin\Service\BotConfigurationService
    public: true
    arguments:
      - '@service_container'