# Delete these routes and define your own shop routes here

ahmedkhd_sylius_bot_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: Ahmedkhd\SyliusBotPlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

ahmedkhd_sylius_bot_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: Ahmedkhd\SyliusBotPlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
