imports:
  - { resource: '@SyliusBotPlugin/Resources/config/services.yml' }
  - { resource: '@SyliusBotPlugin/Resources/config/packages/sylius_resource.yml' }
  - { resource: '@SyliusBotPlugin/Resources/config/packages/grid.yml' }
  - { resource: '@SyliusBotPlugin/Resources/config/packages/twig.yml' }
